name: "Home Lab Everywhere"
version: "1.5.4"
slug: hle
description: "Expose homelab services via HLE tunnels with built-in SSO"
url: "https://github.com/hle-world/ha-addon"

arch:
  - aarch64
  - amd64
  - armv7

startup: application
boot: auto
init: false

ingress: true
ingress_port: 8099
panel_icon: mdi:tunnel
panel_title: HLE

options:
  api_key: ""

schema:
  api_key: password

map:
  - data

image: "ghcr.io/hle-world/ha-addon"
